#!/usr/bin/awk -f

function hamming(s, t,    n,m,S,T,d) {
  n = split(s, S, //)
  m = split(t, T, //)

  d = 0
  for(; n > 0; n--)  {
    d += S[n] != T[n] ? 1 : 0;
  }

  return d;
}

{ print hamming($1, $2), $0 }
