#!/bin/bash

: load cmdline

function r {
  "$@" 3>&1 | od -t x1 -An -v | tr -d '[:space:]'

  return "${PIPESTATUS[0]}"
}

function test {
  [[ $(r cmdline__p__arguments__short_composed 'x:x:x:1;y:y:y:0' -yx a) = "$(r printf '2y\0x:a\0')" ]] || return 1
  [[ $(r cmdline__p__arguments__short_composed 'x:x:x:1;y:y:y:0' -xy a) = "$(r printf '1x:y\0')" ]] || return 1
  [[ $(r cmdline__p__arguments__short_composed 'x:x:x:2;y:y:y:0' -xy a) = "$(r printf '2x:y\0x:a\0')" ]] || return 1

  r cmdline__p__arguments__short_composed 'x:x:x:2;y:y:y:0' -xy >/dev/null && return 1
  r cmdline__p__arguments__short_composed 'x:x:x:2;y:y:y:-1' -x -y >/dev/null && return 1

  return 0
}

test
