#!/bin/bash

: load cmdline


function test {
  cmdline__p__consume_arguments 'x:x:x:1' --x a >/dev/null || return 1
  cmdline__p__consume_arguments 'x:x:x:2' --x a b >/dev/null || return 1
  cmdline__p__consume_arguments 'x:x:x:2' --x a b --x c d >/dev/null || return 1
  cmdline__p__consume_arguments 'x:x:x:2;y:y:y:1' --x a b --y c >/dev/null || return 1

  cmdline__p__consume_arguments 'x:x:x:1' --y >/dev/null && return 1
  cmdline__p__consume_arguments 'x:x:x:-1' --y >/dev/null && return 1

  return 0
}

test
