#!/bin/bash

: load http

function test {
  [[ $(http.url-parse 'http://netloc') = 'http:::netloc:80:/::' ]] || return 1
  [[ $(http.url-parse 'https://netloc') = 'https:::netloc:443:/::' ]] || return 1
  [[ $(http.url-parse '//netloc') = ':::netloc::/::' ]] || return 1
  [[ $(http.url-parse '//username:password@netloc') = ':username:password:netloc::/::' ]] || return 1
  [[ $(http.url-parse '///path') = ':::::///path::' ]] || return 1
  [[ $(http.url-parse 'http://username:password@netloc/path?query=string#fragment') = 'http:username:password:netloc:80:/path:query=string:fragment' ]] || return 1
  [[ $(http.url-parse 'http://netloc/path?query=string#fragment') = 'http:::netloc:80:/path:query=string:fragment' ]] || return 1
  [[ $(http.url-parse 'http://username:password@netloc?query=string#fragment') = 'http:username:password:netloc:80:/:query=string:fragment' ]] || return 1
  [[ $(http.url-parse 'http://netloc/path#fragment') = 'http:::netloc:80:/path::fragment' ]] || return 1

  return 0
}

test
