#!/bin/bash

: load http

function test {
  [[ $(http__form_url_encode '123') = '123' ]] || return 1
  [[ $(http__form_url_encode 'abc') = 'abc' ]] || return 1
  [[ $(http__form_url_encode ':;#') = '%3A%3B%23' ]] || return 1
  [[ $(http__form_url_encode 'á') = 'á' ]] || return 1

  return 0
}

test
