#!/bin/bash

: load template

function test {
  [[ $(printf 'foo'      | foo=bar template__simple) = 'foo'  ]] || return 1
  [[ $(printf '$foo'     | foo=bar template__simple) = 'bar'  ]] || return 1
  [[ $(printf '${foo}'   | foo=bar template__simple) = 'bar'  ]] || return 1
  [[ $(printf '${foo}s'  | foo=bar template__simple) = 'bars' ]] || return 1

  printf '$%%'      | template__simple && return 1
  printf '${foo{'   | template__simple && return 1
  printf '$'        | template__simple && return 1
  printf '${'       | template__simple && return 1

  return 0
}

test
