#!/bin/bash

: load bytes
: load regex

function test {
  typeset i character regex
  typeset -a characters

  for character in {1..255}; do
    IFS= read -rd '' character < <(bytes.chr "$character");
    
    printf -v 'characters[i++]' %b "$character"
  done

  for character in "${characters[@]}"; do
      IFS= read -rd '' regex < <(regex.quote "$character");

      [[ $(printf %s "$character" | sed "s/$regex//") ]] && return 1
  done

  return 0
}

test "$@"
